/*
 * generated by Xtext 2.17.1
 */
package co.unal.photos.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SoftgalleryProposalProvider extends AbstractSoftgalleryProposalProvider {
}
