/*
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SoftGalleryLanguageStandaloneSetup extends SoftGalleryLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new SoftGalleryLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
