/*
 * generated by Xtext 2.17.1
 */
package co.unal.photos.ui.tests;

import co.unal.photos.ui.internal.PhotosActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SoftgalleryUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PhotosActivator.getInstance().getInjector("co.unal.photos.Softgallery");
	}

}
