/*
 * generated by Xtext 2.18.0
 */
package co.unal.mdd.photos.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SoftGalleryLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co/unal/mdd/photos/dsl/parser/antlr/internal/InternalSoftGalleryLanguage.tokens");
	}
}
