/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl;

import co.unal.mdd.photos.dsl.AbstractSoftGalleryLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SoftGalleryLanguageRuntimeModule extends AbstractSoftGalleryLanguageRuntimeModule {
}
