/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos.ui.contentassist;

import co.unal.photos.ui.contentassist.AbstractSoftgalleryProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SoftgalleryProposalProvider extends AbstractSoftgalleryProposalProvider {
}
