/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos;

import co.unal.photos.SoftgalleryStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SoftgalleryStandaloneSetup extends SoftgalleryStandaloneSetupGenerated {
  public static void doSetup() {
    new SoftgalleryStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
