/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos.ui;

import co.unal.photos.ui.AbstractSoftgalleryUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SoftgalleryUiModule extends AbstractSoftgalleryUiModule {
  public SoftgalleryUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
