/*
 * generated by Xtext 2.17.1
 */
package co.unal.photos.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSoftgalleryValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(co.unal.photos.softgallery.SoftgalleryPackage.eINSTANCE);
		return result;
	}
}
