/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos.softgallery;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Layer Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.photos.softgallery.LayerSource#getLayerelations <em>Layerelations</em>}</li>
 * </ul>
 *
 * @see co.unal.photos.softgallery.SoftgalleryPackage#getLayerSource()
 * @model
 * @generated
 */
public interface LayerSource extends EObject
{
  /**
   * Returns the value of the '<em><b>Layerelations</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layerelations</em>' attribute list.
   * @see co.unal.photos.softgallery.SoftgalleryPackage#getLayerSource_Layerelations()
   * @model unique="false"
   * @generated
   */
  EList<String> getLayerelations();

} // LayerSource
