/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos.softgallery;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NTier Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.photos.softgallery.NTierTarget#getNtierconnection <em>Ntierconnection</em>}</li>
 * </ul>
 *
 * @see co.unal.photos.softgallery.SoftgalleryPackage#getNTierTarget()
 * @model
 * @generated
 */
public interface NTierTarget extends EObject
{
  /**
   * Returns the value of the '<em><b>Ntierconnection</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.photos.softgallery.NTiersRelations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ntierconnection</em>' containment reference list.
   * @see co.unal.photos.softgallery.SoftgalleryPackage#getNTierTarget_Ntierconnection()
   * @model containment="true"
   * @generated
   */
  EList<NTiersRelations> getNtierconnection();

} // NTierTarget
