/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos.softgallery;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>React Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.photos.softgallery.ReactConfiguration#getDependencies <em>Dependencies</em>}</li>
 *   <li>{@link co.unal.photos.softgallery.ReactConfiguration#getConfigurations <em>Configurations</em>}</li>
 * </ul>
 *
 * @see co.unal.photos.softgallery.SoftgalleryPackage#getReactConfiguration()
 * @model
 * @generated
 */
public interface ReactConfiguration extends EObject
{
  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.photos.softgallery.ReactDependencies}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference list.
   * @see co.unal.photos.softgallery.SoftgalleryPackage#getReactConfiguration_Dependencies()
   * @model containment="true"
   * @generated
   */
  EList<ReactDependencies> getDependencies();

  /**
   * Returns the value of the '<em><b>Configurations</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.photos.softgallery.ReactConfigurations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configurations</em>' containment reference list.
   * @see co.unal.photos.softgallery.SoftgalleryPackage#getReactConfiguration_Configurations()
   * @model containment="true"
   * @generated
   */
  EList<ReactConfigurations> getConfigurations();

} // ReactConfiguration
