/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos.softgallery;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>React Actions Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.photos.softgallery.ReactActionsContent#getReactrelcontent <em>Reactrelcontent</em>}</li>
 * </ul>
 *
 * @see co.unal.photos.softgallery.SoftgalleryPackage#getReactActionsContent()
 * @model
 * @generated
 */
public interface ReactActionsContent extends EObject
{
  /**
   * Returns the value of the '<em><b>Reactrelcontent</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.photos.softgallery.ReactServicesRelation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactrelcontent</em>' containment reference list.
   * @see co.unal.photos.softgallery.SoftgalleryPackage#getReactActionsContent_Reactrelcontent()
   * @model containment="true"
   * @generated
   */
  EList<ReactServicesRelation> getReactrelcontent();

} // ReactActionsContent
