/*
 * generated by Xtext 2.17.1
 */
package co.unal.photos.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SoftgalleryAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co/unal/photos/parser/antlr/internal/InternalSoftgallery.tokens");
	}
}
