/**
 * generated by Xtext 2.18.0
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Architecture Components</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ArchitectureComponents#getArchFeComponent <em>Arch Fe Component</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ArchitectureComponents#getArchBeComponent <em>Arch Be Component</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ArchitectureComponents#getArchPdComponent <em>Arch Pd Component</em>}</li>
 * </ul>
 *
 * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getArchitectureComponents()
 * @model
 * @generated
 */
public interface ArchitectureComponents extends EObject
{
  /**
   * Returns the value of the '<em><b>Arch Fe Component</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.FrontEnd}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arch Fe Component</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getArchitectureComponents_ArchFeComponent()
   * @model containment="true"
   * @generated
   */
  EList<FrontEnd> getArchFeComponent();

  /**
   * Returns the value of the '<em><b>Arch Be Component</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.BackEnd}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arch Be Component</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getArchitectureComponents_ArchBeComponent()
   * @model containment="true"
   * @generated
   */
  EList<BackEnd> getArchBeComponent();

  /**
   * Returns the value of the '<em><b>Arch Pd Component</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.PersistenceDataComponent}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arch Pd Component</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getArchitectureComponents_ArchPdComponent()
   * @model containment="true"
   * @generated
   */
  EList<PersistenceDataComponent> getArchPdComponent();

} // ArchitectureComponents
