/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic Structure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.LogicStructure#getAppComName <em>App Com Name</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.LogicStructure#getLogiccomponents <em>Logiccomponents</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.LogicStructure#getIndexCompName <em>Index Comp Name</em>}</li>
 * </ul>
 *
 * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getLogicStructure()
 * @model
 * @generated
 */
public interface LogicStructure extends EObject
{
  /**
   * Returns the value of the '<em><b>App Com Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>App Com Name</em>' attribute.
   * @see #setAppComName(String)
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getLogicStructure_AppComName()
   * @model
   * @generated
   */
  String getAppComName();

  /**
   * Sets the value of the '{@link co.unal.mdd.photos.dsl.softGalleryLanguage.LogicStructure#getAppComName <em>App Com Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>App Com Name</em>' attribute.
   * @see #getAppComName()
   * @generated
   */
  void setAppComName(String value);

  /**
   * Returns the value of the '<em><b>Logiccomponents</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ComponentClass}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logiccomponents</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getLogicStructure_Logiccomponents()
   * @model containment="true"
   * @generated
   */
  EList<ComponentClass> getLogiccomponents();

  /**
   * Returns the value of the '<em><b>Index Comp Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index Comp Name</em>' attribute.
   * @see #setIndexCompName(String)
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getLogicStructure_IndexCompName()
   * @model
   * @generated
   */
  String getIndexCompName();

  /**
   * Sets the value of the '{@link co.unal.mdd.photos.dsl.softGalleryLanguage.LogicStructure#getIndexCompName <em>Index Comp Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index Comp Name</em>' attribute.
   * @see #getIndexCompName()
   * @generated
   */
  void setIndexCompName(String value);

} // LogicStructure
