/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Photo Actions Functions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.PhotoActionsFunctions#getNameGenerico <em>Name Generico</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.PhotoActionsFunctions#getNamePhoto <em>Name Photo</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.PhotoActionsFunctions#getNameLoad <em>Name Load</em>}</li>
 * </ul>
 *
 * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getPhotoActionsFunctions()
 * @model
 * @generated
 */
public interface PhotoActionsFunctions extends EObject
{
  /**
   * Returns the value of the '<em><b>Name Generico</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Generico</em>' attribute.
   * @see #setNameGenerico(String)
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getPhotoActionsFunctions_NameGenerico()
   * @model
   * @generated
   */
  String getNameGenerico();

  /**
   * Sets the value of the '{@link co.unal.mdd.photos.dsl.softGalleryLanguage.PhotoActionsFunctions#getNameGenerico <em>Name Generico</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Generico</em>' attribute.
   * @see #getNameGenerico()
   * @generated
   */
  void setNameGenerico(String value);

  /**
   * Returns the value of the '<em><b>Name Photo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Photo</em>' attribute.
   * @see #setNamePhoto(String)
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getPhotoActionsFunctions_NamePhoto()
   * @model
   * @generated
   */
  String getNamePhoto();

  /**
   * Sets the value of the '{@link co.unal.mdd.photos.dsl.softGalleryLanguage.PhotoActionsFunctions#getNamePhoto <em>Name Photo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Photo</em>' attribute.
   * @see #getNamePhoto()
   * @generated
   */
  void setNamePhoto(String value);

  /**
   * Returns the value of the '<em><b>Name Load</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Load</em>' attribute.
   * @see #setNameLoad(String)
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getPhotoActionsFunctions_NameLoad()
   * @model
   * @generated
   */
  String getNameLoad();

  /**
   * Sets the value of the '{@link co.unal.mdd.photos.dsl.softGalleryLanguage.PhotoActionsFunctions#getNameLoad <em>Name Load</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Load</em>' attribute.
   * @see #getNameLoad()
   * @generated
   */
  void setNameLoad(String value);

} // PhotoActionsFunctions
