/**
 * generated by Xtext 2.18.0
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Profile Management Functions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ProfileManagementFunctions#getViewprofileName <em>Viewprofile Name</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ProfileManagementFunctions#getEditProfileName <em>Edit Profile Name</em>}</li>
 * </ul>
 *
 * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getProfileManagementFunctions()
 * @model
 * @generated
 */
public interface ProfileManagementFunctions extends EObject
{
  /**
   * Returns the value of the '<em><b>Viewprofile Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Viewprofile Name</em>' attribute.
   * @see #setViewprofileName(String)
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getProfileManagementFunctions_ViewprofileName()
   * @model
   * @generated
   */
  String getViewprofileName();

  /**
   * Sets the value of the '{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ProfileManagementFunctions#getViewprofileName <em>Viewprofile Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Viewprofile Name</em>' attribute.
   * @see #getViewprofileName()
   * @generated
   */
  void setViewprofileName(String value);

  /**
   * Returns the value of the '<em><b>Edit Profile Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edit Profile Name</em>' attribute.
   * @see #setEditProfileName(String)
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getProfileManagementFunctions_EditProfileName()
   * @model
   * @generated
   */
  String getEditProfileName();

  /**
   * Sets the value of the '{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ProfileManagementFunctions#getEditProfileName <em>Edit Profile Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Edit Profile Name</em>' attribute.
   * @see #getEditProfileName()
   * @generated
   */
  void setEditProfileName(String value);

} // ProfileManagementFunctions
