/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>React Service Cont Request</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactServiceContRequest#getReactservrequestprops <em>Reactservrequestprops</em>}</li>
 * </ul>
 *
 * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactServiceContRequest()
 * @model
 * @generated
 */
public interface ReactServiceContRequest extends EObject
{
  /**
   * Returns the value of the '<em><b>Reactservrequestprops</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactServiceRequestProps}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactservrequestprops</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactServiceContRequest_Reactservrequestprops()
   * @model containment="true"
   * @generated
   */
  EList<ReactServiceRequestProps> getReactservrequestprops();

} // ReactServiceContRequest
