/**
 * generated by Xtext 2.18.0
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>React Sub Modules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactSubModules#getReactmodulesconf <em>Reactmodulesconf</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactSubModules#getReactmodulescomp <em>Reactmodulescomp</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactSubModules#getReactmodulesact <em>Reactmodulesact</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactSubModules#getReactmoduleslib <em>Reactmoduleslib</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactSubModules#getReactmodulesinf <em>Reactmodulesinf</em>}</li>
 * </ul>
 *
 * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactSubModules()
 * @model
 * @generated
 */
public interface ReactSubModules extends EObject
{
  /**
   * Returns the value of the '<em><b>Reactmodulesconf</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactConfiguration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactmodulesconf</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactSubModules_Reactmodulesconf()
   * @model containment="true"
   * @generated
   */
  EList<ReactConfiguration> getReactmodulesconf();

  /**
   * Returns the value of the '<em><b>Reactmodulescomp</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactComponents}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactmodulescomp</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactSubModules_Reactmodulescomp()
   * @model containment="true"
   * @generated
   */
  EList<ReactComponents> getReactmodulescomp();

  /**
   * Returns the value of the '<em><b>Reactmodulesact</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactActions}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactmodulesact</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactSubModules_Reactmodulesact()
   * @model containment="true"
   * @generated
   */
  EList<ReactActions> getReactmodulesact();

  /**
   * Returns the value of the '<em><b>Reactmoduleslib</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactLibraries}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactmoduleslib</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactSubModules_Reactmoduleslib()
   * @model containment="true"
   * @generated
   */
  EList<ReactLibraries> getReactmoduleslib();

  /**
   * Returns the value of the '<em><b>Reactmodulesinf</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ReactInfo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactmodulesinf</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getReactSubModules_Reactmodulesinf()
   * @model containment="true"
   * @generated
   */
  EList<ReactInfo> getReactmodulesinf();

} // ReactSubModules
