/**
 * generated by Xtext 2.18.0
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UI Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.UIContent#getComponentcontent <em>Componentcontent</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.UIContent#getSubcomponentcontent <em>Subcomponentcontent</em>}</li>
 * </ul>
 *
 * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getUIContent()
 * @model
 * @generated
 */
public interface UIContent extends EObject
{
  /**
   * Returns the value of the '<em><b>Componentcontent</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.ViewComponentCont}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Componentcontent</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getUIContent_Componentcontent()
   * @model containment="true"
   * @generated
   */
  EList<ViewComponentCont> getComponentcontent();

  /**
   * Returns the value of the '<em><b>Subcomponentcontent</b></em>' containment reference list.
   * The list contents are of type {@link co.unal.mdd.photos.dsl.softGalleryLanguage.SubcomponentCont}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subcomponentcontent</em>' containment reference list.
   * @see co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage#getUIContent_Subcomponentcontent()
   * @model containment="true"
   * @generated
   */
  EList<SubcomponentCont> getSubcomponentcontent();

} // UIContent
