/*
 * generated by Xtext 2.17.1
 */
package co.unal.photos.ui;

import co.unal.photos.ui.internal.PhotosActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SoftgalleryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PhotosActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PhotosActivator activator = PhotosActivator.getInstance();
		return activator != null ? activator.getInjector(PhotosActivator.CO_UNAL_PHOTOS_SOFTGALLERY) : null;
	}

}
