/**
 * generated by Xtext 2.17.1
 */
package co.unal.photos.softgallery.impl;

import co.unal.photos.softgallery.AlbumManagement;
import co.unal.photos.softgallery.AppAccess;
import co.unal.photos.softgallery.Functionalities;
import co.unal.photos.softgallery.LandingActions;
import co.unal.photos.softgallery.PhotoActions;
import co.unal.photos.softgallery.ProfileManagement;
import co.unal.photos.softgallery.SoftgalleryPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Functionalities</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.unal.photos.softgallery.impl.FunctionalitiesImpl#getFunctions <em>Functions</em>}</li>
 *   <li>{@link co.unal.photos.softgallery.impl.FunctionalitiesImpl#getElements <em>Elements</em>}</li>
 *   <li>{@link co.unal.photos.softgallery.impl.FunctionalitiesImpl#getItems <em>Items</em>}</li>
 *   <li>{@link co.unal.photos.softgallery.impl.FunctionalitiesImpl#getResources <em>Resources</em>}</li>
 *   <li>{@link co.unal.photos.softgallery.impl.FunctionalitiesImpl#getAditionals <em>Aditionals</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FunctionalitiesImpl extends MinimalEObjectImpl.Container implements Functionalities
{
  /**
   * The cached value of the '{@link #getFunctions() <em>Functions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunctions()
   * @generated
   * @ordered
   */
  protected EList<ProfileManagement> functions;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<AppAccess> elements;

  /**
   * The cached value of the '{@link #getItems() <em>Items</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItems()
   * @generated
   * @ordered
   */
  protected EList<AlbumManagement> items;

  /**
   * The cached value of the '{@link #getResources() <em>Resources</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResources()
   * @generated
   * @ordered
   */
  protected EList<PhotoActions> resources;

  /**
   * The cached value of the '{@link #getAditionals() <em>Aditionals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAditionals()
   * @generated
   * @ordered
   */
  protected EList<LandingActions> aditionals;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionalitiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftgalleryPackage.Literals.FUNCTIONALITIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ProfileManagement> getFunctions()
  {
    if (functions == null)
    {
      functions = new EObjectContainmentEList<ProfileManagement>(ProfileManagement.class, this, SoftgalleryPackage.FUNCTIONALITIES__FUNCTIONS);
    }
    return functions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AppAccess> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<AppAccess>(AppAccess.class, this, SoftgalleryPackage.FUNCTIONALITIES__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AlbumManagement> getItems()
  {
    if (items == null)
    {
      items = new EObjectContainmentEList<AlbumManagement>(AlbumManagement.class, this, SoftgalleryPackage.FUNCTIONALITIES__ITEMS);
    }
    return items;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PhotoActions> getResources()
  {
    if (resources == null)
    {
      resources = new EObjectContainmentEList<PhotoActions>(PhotoActions.class, this, SoftgalleryPackage.FUNCTIONALITIES__RESOURCES);
    }
    return resources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LandingActions> getAditionals()
  {
    if (aditionals == null)
    {
      aditionals = new EObjectContainmentEList<LandingActions>(LandingActions.class, this, SoftgalleryPackage.FUNCTIONALITIES__ADITIONALS);
    }
    return aditionals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SoftgalleryPackage.FUNCTIONALITIES__FUNCTIONS:
        return ((InternalEList<?>)getFunctions()).basicRemove(otherEnd, msgs);
      case SoftgalleryPackage.FUNCTIONALITIES__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
      case SoftgalleryPackage.FUNCTIONALITIES__ITEMS:
        return ((InternalEList<?>)getItems()).basicRemove(otherEnd, msgs);
      case SoftgalleryPackage.FUNCTIONALITIES__RESOURCES:
        return ((InternalEList<?>)getResources()).basicRemove(otherEnd, msgs);
      case SoftgalleryPackage.FUNCTIONALITIES__ADITIONALS:
        return ((InternalEList<?>)getAditionals()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SoftgalleryPackage.FUNCTIONALITIES__FUNCTIONS:
        return getFunctions();
      case SoftgalleryPackage.FUNCTIONALITIES__ELEMENTS:
        return getElements();
      case SoftgalleryPackage.FUNCTIONALITIES__ITEMS:
        return getItems();
      case SoftgalleryPackage.FUNCTIONALITIES__RESOURCES:
        return getResources();
      case SoftgalleryPackage.FUNCTIONALITIES__ADITIONALS:
        return getAditionals();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SoftgalleryPackage.FUNCTIONALITIES__FUNCTIONS:
        getFunctions().clear();
        getFunctions().addAll((Collection<? extends ProfileManagement>)newValue);
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends AppAccess>)newValue);
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__ITEMS:
        getItems().clear();
        getItems().addAll((Collection<? extends AlbumManagement>)newValue);
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__RESOURCES:
        getResources().clear();
        getResources().addAll((Collection<? extends PhotoActions>)newValue);
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__ADITIONALS:
        getAditionals().clear();
        getAditionals().addAll((Collection<? extends LandingActions>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SoftgalleryPackage.FUNCTIONALITIES__FUNCTIONS:
        getFunctions().clear();
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__ELEMENTS:
        getElements().clear();
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__ITEMS:
        getItems().clear();
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__RESOURCES:
        getResources().clear();
        return;
      case SoftgalleryPackage.FUNCTIONALITIES__ADITIONALS:
        getAditionals().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SoftgalleryPackage.FUNCTIONALITIES__FUNCTIONS:
        return functions != null && !functions.isEmpty();
      case SoftgalleryPackage.FUNCTIONALITIES__ELEMENTS:
        return elements != null && !elements.isEmpty();
      case SoftgalleryPackage.FUNCTIONALITIES__ITEMS:
        return items != null && !items.isEmpty();
      case SoftgalleryPackage.FUNCTIONALITIES__RESOURCES:
        return resources != null && !resources.isEmpty();
      case SoftgalleryPackage.FUNCTIONALITIES__ADITIONALS:
        return aditionals != null && !aditionals.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FunctionalitiesImpl
