/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage.impl;

import co.unal.mdd.photos.dsl.softGalleryLanguage.AppAccessFunctions;
import co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>App Access Functions</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.AppAccessFunctionsImpl#getLoginName <em>Login Name</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.AppAccessFunctionsImpl#getRegisterName <em>Register Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AppAccessFunctionsImpl extends MinimalEObjectImpl.Container implements AppAccessFunctions
{
  /**
   * The default value of the '{@link #getLoginName() <em>Login Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoginName()
   * @generated
   * @ordered
   */
  protected static final String LOGIN_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLoginName() <em>Login Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoginName()
   * @generated
   * @ordered
   */
  protected String loginName = LOGIN_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getRegisterName() <em>Register Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegisterName()
   * @generated
   * @ordered
   */
  protected static final String REGISTER_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRegisterName() <em>Register Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegisterName()
   * @generated
   * @ordered
   */
  protected String registerName = REGISTER_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AppAccessFunctionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftGalleryLanguagePackage.Literals.APP_ACCESS_FUNCTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLoginName()
  {
    return loginName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLoginName(String newLoginName)
  {
    String oldLoginName = loginName;
    loginName = newLoginName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__LOGIN_NAME, oldLoginName, loginName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRegisterName()
  {
    return registerName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRegisterName(String newRegisterName)
  {
    String oldRegisterName = registerName;
    registerName = newRegisterName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__REGISTER_NAME, oldRegisterName, registerName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__LOGIN_NAME:
        return getLoginName();
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__REGISTER_NAME:
        return getRegisterName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__LOGIN_NAME:
        setLoginName((String)newValue);
        return;
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__REGISTER_NAME:
        setRegisterName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__LOGIN_NAME:
        setLoginName(LOGIN_NAME_EDEFAULT);
        return;
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__REGISTER_NAME:
        setRegisterName(REGISTER_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__LOGIN_NAME:
        return LOGIN_NAME_EDEFAULT == null ? loginName != null : !LOGIN_NAME_EDEFAULT.equals(loginName);
      case SoftGalleryLanguagePackage.APP_ACCESS_FUNCTIONS__REGISTER_NAME:
        return REGISTER_NAME_EDEFAULT == null ? registerName != null : !REGISTER_NAME_EDEFAULT.equals(registerName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (loginName: ");
    result.append(loginName);
    result.append(", registerName: ");
    result.append(registerName);
    result.append(')');
    return result.toString();
  }

} //AppAccessFunctionsImpl
