/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage.impl;

import co.unal.mdd.photos.dsl.softGalleryLanguage.BusinessLogicSegments;
import co.unal.mdd.photos.dsl.softGalleryLanguage.ControllerSegmentElement;
import co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage;
import co.unal.mdd.photos.dsl.softGalleryLanguage.SpecificationSegmentElement;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Business Logic Segments</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.BusinessLogicSegmentsImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.BusinessLogicSegmentsImpl#getControllerSegmentElement <em>Controller Segment Element</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.BusinessLogicSegmentsImpl#getSpecificationSegmentElement <em>Specification Segment Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BusinessLogicSegmentsImpl extends MinimalEObjectImpl.Container implements BusinessLogicSegments
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getControllerSegmentElement() <em>Controller Segment Element</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getControllerSegmentElement()
   * @generated
   * @ordered
   */
  protected EList<ControllerSegmentElement> controllerSegmentElement;

  /**
   * The cached value of the '{@link #getSpecificationSegmentElement() <em>Specification Segment Element</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecificationSegmentElement()
   * @generated
   * @ordered
   */
  protected EList<SpecificationSegmentElement> specificationSegmentElement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BusinessLogicSegmentsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftGalleryLanguagePackage.Literals.BUSINESS_LOGIC_SEGMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ControllerSegmentElement> getControllerSegmentElement()
  {
    if (controllerSegmentElement == null)
    {
      controllerSegmentElement = new EObjectContainmentEList<ControllerSegmentElement>(ControllerSegmentElement.class, this, SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__CONTROLLER_SEGMENT_ELEMENT);
    }
    return controllerSegmentElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SpecificationSegmentElement> getSpecificationSegmentElement()
  {
    if (specificationSegmentElement == null)
    {
      specificationSegmentElement = new EObjectContainmentEList<SpecificationSegmentElement>(SpecificationSegmentElement.class, this, SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__SPECIFICATION_SEGMENT_ELEMENT);
    }
    return specificationSegmentElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__CONTROLLER_SEGMENT_ELEMENT:
        return ((InternalEList<?>)getControllerSegmentElement()).basicRemove(otherEnd, msgs);
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__SPECIFICATION_SEGMENT_ELEMENT:
        return ((InternalEList<?>)getSpecificationSegmentElement()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__NAME:
        return getName();
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__CONTROLLER_SEGMENT_ELEMENT:
        return getControllerSegmentElement();
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__SPECIFICATION_SEGMENT_ELEMENT:
        return getSpecificationSegmentElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__NAME:
        setName((String)newValue);
        return;
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__CONTROLLER_SEGMENT_ELEMENT:
        getControllerSegmentElement().clear();
        getControllerSegmentElement().addAll((Collection<? extends ControllerSegmentElement>)newValue);
        return;
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__SPECIFICATION_SEGMENT_ELEMENT:
        getSpecificationSegmentElement().clear();
        getSpecificationSegmentElement().addAll((Collection<? extends SpecificationSegmentElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__CONTROLLER_SEGMENT_ELEMENT:
        getControllerSegmentElement().clear();
        return;
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__SPECIFICATION_SEGMENT_ELEMENT:
        getSpecificationSegmentElement().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__CONTROLLER_SEGMENT_ELEMENT:
        return controllerSegmentElement != null && !controllerSegmentElement.isEmpty();
      case SoftGalleryLanguagePackage.BUSINESS_LOGIC_SEGMENTS__SPECIFICATION_SEGMENT_ELEMENT:
        return specificationSegmentElement != null && !specificationSegmentElement.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //BusinessLogicSegmentsImpl
