/**
 * generated by Xtext 2.18.0
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage.impl;

import co.unal.mdd.photos.dsl.softGalleryLanguage.DataPersistenceSegments;
import co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Persistence Segments</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.DataPersistenceSegmentsImpl#getPostSName <em>Post SName</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.DataPersistenceSegmentsImpl#getAmazonSName <em>Amazon SName</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataPersistenceSegmentsImpl extends MinimalEObjectImpl.Container implements DataPersistenceSegments
{
  /**
   * The default value of the '{@link #getPostSName() <em>Post SName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostSName()
   * @generated
   * @ordered
   */
  protected static final String POST_SNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPostSName() <em>Post SName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostSName()
   * @generated
   * @ordered
   */
  protected String postSName = POST_SNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAmazonSName() <em>Amazon SName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmazonSName()
   * @generated
   * @ordered
   */
  protected static final String AMAZON_SNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAmazonSName() <em>Amazon SName</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmazonSName()
   * @generated
   * @ordered
   */
  protected String amazonSName = AMAZON_SNAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataPersistenceSegmentsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftGalleryLanguagePackage.Literals.DATA_PERSISTENCE_SEGMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPostSName()
  {
    return postSName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPostSName(String newPostSName)
  {
    String oldPostSName = postSName;
    postSName = newPostSName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__POST_SNAME, oldPostSName, postSName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAmazonSName()
  {
    return amazonSName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAmazonSName(String newAmazonSName)
  {
    String oldAmazonSName = amazonSName;
    amazonSName = newAmazonSName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__AMAZON_SNAME, oldAmazonSName, amazonSName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__POST_SNAME:
        return getPostSName();
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__AMAZON_SNAME:
        return getAmazonSName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__POST_SNAME:
        setPostSName((String)newValue);
        return;
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__AMAZON_SNAME:
        setAmazonSName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__POST_SNAME:
        setPostSName(POST_SNAME_EDEFAULT);
        return;
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__AMAZON_SNAME:
        setAmazonSName(AMAZON_SNAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__POST_SNAME:
        return POST_SNAME_EDEFAULT == null ? postSName != null : !POST_SNAME_EDEFAULT.equals(postSName);
      case SoftGalleryLanguagePackage.DATA_PERSISTENCE_SEGMENTS__AMAZON_SNAME:
        return AMAZON_SNAME_EDEFAULT == null ? amazonSName != null : !AMAZON_SNAME_EDEFAULT.equals(amazonSName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (postSName: ");
    result.append(postSName);
    result.append(", amazonSName: ");
    result.append(amazonSName);
    result.append(')');
    return result.toString();
  }

} //DataPersistenceSegmentsImpl
