/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage.impl;

import co.unal.mdd.photos.dsl.softGalleryLanguage.ReactFunctions;
import co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>React Functions</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.ReactFunctionsImpl#getComponentclass <em>Componentclass</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.ReactFunctionsImpl#getLifecycleclass <em>Lifecycleclass</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.ReactFunctionsImpl#getRenderclass <em>Renderclass</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReactFunctionsImpl extends MinimalEObjectImpl.Container implements ReactFunctions
{
  /**
   * The cached value of the '{@link #getComponentclass() <em>Componentclass</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComponentclass()
   * @generated
   * @ordered
   */
  protected EList<EObject> componentclass;

  /**
   * The cached value of the '{@link #getLifecycleclass() <em>Lifecycleclass</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLifecycleclass()
   * @generated
   * @ordered
   */
  protected EList<String> lifecycleclass;

  /**
   * The cached value of the '{@link #getRenderclass() <em>Renderclass</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRenderclass()
   * @generated
   * @ordered
   */
  protected EList<String> renderclass;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReactFunctionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftGalleryLanguagePackage.Literals.REACT_FUNCTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EObject> getComponentclass()
  {
    if (componentclass == null)
    {
      componentclass = new EObjectContainmentEList<EObject>(EObject.class, this, SoftGalleryLanguagePackage.REACT_FUNCTIONS__COMPONENTCLASS);
    }
    return componentclass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getLifecycleclass()
  {
    if (lifecycleclass == null)
    {
      lifecycleclass = new EDataTypeEList<String>(String.class, this, SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS);
    }
    return lifecycleclass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getRenderclass()
  {
    if (renderclass == null)
    {
      renderclass = new EDataTypeEList<String>(String.class, this, SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS);
    }
    return renderclass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__COMPONENTCLASS:
        return ((InternalEList<?>)getComponentclass()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__COMPONENTCLASS:
        return getComponentclass();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        return getLifecycleclass();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        return getRenderclass();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__COMPONENTCLASS:
        getComponentclass().clear();
        getComponentclass().addAll((Collection<? extends EObject>)newValue);
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        getLifecycleclass().clear();
        getLifecycleclass().addAll((Collection<? extends String>)newValue);
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        getRenderclass().clear();
        getRenderclass().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__COMPONENTCLASS:
        getComponentclass().clear();
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        getLifecycleclass().clear();
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        getRenderclass().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__COMPONENTCLASS:
        return componentclass != null && !componentclass.isEmpty();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        return lifecycleclass != null && !lifecycleclass.isEmpty();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        return renderclass != null && !renderclass.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (lifecycleclass: ");
    result.append(lifecycleclass);
    result.append(", renderclass: ");
    result.append(renderclass);
    result.append(')');
    return result.toString();
  }

} //ReactFunctionsImpl
