/**
 * generated by Xtext 2.18.0
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage.impl;

import co.unal.mdd.photos.dsl.softGalleryLanguage.ReactConstructor;
import co.unal.mdd.photos.dsl.softGalleryLanguage.ReactCoreFunctions;
import co.unal.mdd.photos.dsl.softGalleryLanguage.ReactFunctions;
import co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>React Functions</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.ReactFunctionsImpl#getReactconstructors <em>Reactconstructors</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.ReactFunctionsImpl#getLifecycleclass <em>Lifecycleclass</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.ReactFunctionsImpl#getReactcorefuncs <em>Reactcorefuncs</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.ReactFunctionsImpl#getRenderclass <em>Renderclass</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReactFunctionsImpl extends MinimalEObjectImpl.Container implements ReactFunctions
{
  /**
   * The cached value of the '{@link #getReactconstructors() <em>Reactconstructors</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReactconstructors()
   * @generated
   * @ordered
   */
  protected EList<ReactConstructor> reactconstructors;

  /**
   * The cached value of the '{@link #getLifecycleclass() <em>Lifecycleclass</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLifecycleclass()
   * @generated
   * @ordered
   */
  protected EList<String> lifecycleclass;

  /**
   * The cached value of the '{@link #getReactcorefuncs() <em>Reactcorefuncs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReactcorefuncs()
   * @generated
   * @ordered
   */
  protected EList<ReactCoreFunctions> reactcorefuncs;

  /**
   * The cached value of the '{@link #getRenderclass() <em>Renderclass</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRenderclass()
   * @generated
   * @ordered
   */
  protected EList<String> renderclass;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReactFunctionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftGalleryLanguagePackage.Literals.REACT_FUNCTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ReactConstructor> getReactconstructors()
  {
    if (reactconstructors == null)
    {
      reactconstructors = new EObjectContainmentEList<ReactConstructor>(ReactConstructor.class, this, SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCONSTRUCTORS);
    }
    return reactconstructors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getLifecycleclass()
  {
    if (lifecycleclass == null)
    {
      lifecycleclass = new EDataTypeEList<String>(String.class, this, SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS);
    }
    return lifecycleclass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ReactCoreFunctions> getReactcorefuncs()
  {
    if (reactcorefuncs == null)
    {
      reactcorefuncs = new EObjectContainmentEList<ReactCoreFunctions>(ReactCoreFunctions.class, this, SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCOREFUNCS);
    }
    return reactcorefuncs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getRenderclass()
  {
    if (renderclass == null)
    {
      renderclass = new EDataTypeEList<String>(String.class, this, SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS);
    }
    return renderclass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCONSTRUCTORS:
        return ((InternalEList<?>)getReactconstructors()).basicRemove(otherEnd, msgs);
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCOREFUNCS:
        return ((InternalEList<?>)getReactcorefuncs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCONSTRUCTORS:
        return getReactconstructors();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        return getLifecycleclass();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCOREFUNCS:
        return getReactcorefuncs();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        return getRenderclass();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCONSTRUCTORS:
        getReactconstructors().clear();
        getReactconstructors().addAll((Collection<? extends ReactConstructor>)newValue);
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        getLifecycleclass().clear();
        getLifecycleclass().addAll((Collection<? extends String>)newValue);
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCOREFUNCS:
        getReactcorefuncs().clear();
        getReactcorefuncs().addAll((Collection<? extends ReactCoreFunctions>)newValue);
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        getRenderclass().clear();
        getRenderclass().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCONSTRUCTORS:
        getReactconstructors().clear();
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        getLifecycleclass().clear();
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCOREFUNCS:
        getReactcorefuncs().clear();
        return;
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        getRenderclass().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCONSTRUCTORS:
        return reactconstructors != null && !reactconstructors.isEmpty();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__LIFECYCLECLASS:
        return lifecycleclass != null && !lifecycleclass.isEmpty();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__REACTCOREFUNCS:
        return reactcorefuncs != null && !reactcorefuncs.isEmpty();
      case SoftGalleryLanguagePackage.REACT_FUNCTIONS__RENDERCLASS:
        return renderclass != null && !renderclass.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (lifecycleclass: ");
    result.append(lifecycleclass);
    result.append(", renderclass: ");
    result.append(renderclass);
    result.append(')');
    return result.toString();
  }

} //ReactFunctionsImpl
