/**
 * generated by Xtext 2.17.1
 */
package co.unal.mdd.photos.dsl.softGalleryLanguage.impl;

import co.unal.mdd.photos.dsl.softGalleryLanguage.SoftGalleryLanguagePackage;
import co.unal.mdd.photos.dsl.softGalleryLanguage.SubcomponentCont;
import co.unal.mdd.photos.dsl.softGalleryLanguage.UIContent;
import co.unal.mdd.photos.dsl.softGalleryLanguage.ViewComponentCont;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UI Content</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.UIContentImpl#getComponentcontent <em>Componentcontent</em>}</li>
 *   <li>{@link co.unal.mdd.photos.dsl.softGalleryLanguage.impl.UIContentImpl#getSubcomponentcontent <em>Subcomponentcontent</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UIContentImpl extends MinimalEObjectImpl.Container implements UIContent
{
  /**
   * The cached value of the '{@link #getComponentcontent() <em>Componentcontent</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComponentcontent()
   * @generated
   * @ordered
   */
  protected EList<ViewComponentCont> componentcontent;

  /**
   * The cached value of the '{@link #getSubcomponentcontent() <em>Subcomponentcontent</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubcomponentcontent()
   * @generated
   * @ordered
   */
  protected EList<SubcomponentCont> subcomponentcontent;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UIContentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SoftGalleryLanguagePackage.Literals.UI_CONTENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ViewComponentCont> getComponentcontent()
  {
    if (componentcontent == null)
    {
      componentcontent = new EObjectContainmentEList<ViewComponentCont>(ViewComponentCont.class, this, SoftGalleryLanguagePackage.UI_CONTENT__COMPONENTCONTENT);
    }
    return componentcontent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SubcomponentCont> getSubcomponentcontent()
  {
    if (subcomponentcontent == null)
    {
      subcomponentcontent = new EObjectContainmentEList<SubcomponentCont>(SubcomponentCont.class, this, SoftGalleryLanguagePackage.UI_CONTENT__SUBCOMPONENTCONTENT);
    }
    return subcomponentcontent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.UI_CONTENT__COMPONENTCONTENT:
        return ((InternalEList<?>)getComponentcontent()).basicRemove(otherEnd, msgs);
      case SoftGalleryLanguagePackage.UI_CONTENT__SUBCOMPONENTCONTENT:
        return ((InternalEList<?>)getSubcomponentcontent()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.UI_CONTENT__COMPONENTCONTENT:
        return getComponentcontent();
      case SoftGalleryLanguagePackage.UI_CONTENT__SUBCOMPONENTCONTENT:
        return getSubcomponentcontent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.UI_CONTENT__COMPONENTCONTENT:
        getComponentcontent().clear();
        getComponentcontent().addAll((Collection<? extends ViewComponentCont>)newValue);
        return;
      case SoftGalleryLanguagePackage.UI_CONTENT__SUBCOMPONENTCONTENT:
        getSubcomponentcontent().clear();
        getSubcomponentcontent().addAll((Collection<? extends SubcomponentCont>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.UI_CONTENT__COMPONENTCONTENT:
        getComponentcontent().clear();
        return;
      case SoftGalleryLanguagePackage.UI_CONTENT__SUBCOMPONENTCONTENT:
        getSubcomponentcontent().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SoftGalleryLanguagePackage.UI_CONTENT__COMPONENTCONTENT:
        return componentcontent != null && !componentcontent.isEmpty();
      case SoftGalleryLanguagePackage.UI_CONTENT__SUBCOMPONENTCONTENT:
        return subcomponentcontent != null && !subcomponentcontent.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //UIContentImpl
